twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic: cmd_vel_nav
        timeout: 0.5
        priority: 10
      magnetic_line:
        topic: cmd_vel_line
        timeout: 0.3
        priority: 70
      web:
        topic: cmd_vel_web
        timeout: 0.5
        priority: 80
      pause:
        topic: cmd_vel_pause
        timeout: 0.3
        priority: 90
      keyboard:
        topic: cmd_vel_key
        timeout: 0.5
        priority: 100
    locks:
      emergency:
        topic: emergency/bumper
        timeout: 0.0
        priority: 255
