twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic: cmd_vel_nav
        timeout: 0.5
        priority: 10
      docking:
        topic: cmd_vel_dock
        timeout: 0.5
        priority: 70
      web:
        topic: cmd_vel_web
        timeout: 0.5
        priority: 80
      keyboard:
        topic: cmd_vel_key
        timeout: 0.5
        priority: 100
    locks:
      emergency:
        topic: emergency/bumper
        timeout: 0.0
        priority: 255
