stations:
  S01:
    pre_dock_pose_A:
      frame_id: map
      x: 2.10
      y: 1.50
      yaw: 0.0
    dock_start_A:
      frame_id: map
      x: 2.10
      y: 1.50
      yaw: 0.0
    dock_final_B:
      frame_id: map
      x: 2.60
      y: 1.50
      yaw: 0.0
    undock_pose_A:
      frame_id: map
      x: 2.10
      y: 1.50
      yaw: 0.0
