mission_supervisor:
  ros__parameters:
    use_sim_time: false
    station_database: ""
    nav_action_name: navigate_to_pose
    dock_action_name: /dock
    cmd_vel_nav_topic: /cmd_vel_nav
    cmd_vel_dock_topic: /cmd_vel_dock
    nav_to_a_timeout_sec: 180.0
    nav_to_next_timeout_sec: 180.0
    docking_timeout_sec: 90.0
    cargo_wait_timeout_sec: 600.0
    dock_max_speed: 0.06
